# @api = http://localhost:5004/api
@api = https://topomojo.cyberforce.site/api
@json = Content-Type: application/json
@apikey = x-api-key: MJmWAjxMrTBNPwUtFzlJwW6smZthpRaY
#123456

###
GET {{api}}/workspaces


###
POST http://localhost:5000/api/resource/devimport
{{json}}

{
    "Apis": [ "topomojo-api" ],
    "Clients": [
        {
            "Id": "topomojo-ui",
            "DisplayName": "",
            "GrantType": "authorization_code",
            "Scopes": "openid profile topomojo-api",
            "Secret": "",
            "RedirectUrl": "http://localhost:4200/oidc"
        },
        {
            "Id": "topomojo-swagger",
            "GrantType": "authorization_code",
            "Scopes": "openid topomojo-api",
            "RedirectUrl": "http://localhost:5004/api/oauth2-redirect.html"
        }
    ]
}

###
POST {{api}}/engine/register
{{apikey}}
{{json}}

{
    "subjectId": "74d8b503-50be-40ec-a553-895a6afc1f37",
    "subjectName": "Jeff.Mattson",
    "resourceId": "e4b2d5a9-e0db-4562-9366-cbc0f69c95aa"
}

###
DELETE {{api}}/engine/gamespace/edc58568-d7bf-4563-988e-0725b5a17b7d
{{apikey}}
