# Example tests with REST Client (VSCode Extension)

@url = http://localhost:5004/api
@json = content-type: application/json
@auth = Authorization: Bearer {{login.response.body.access_token}}

###

# @name login
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=dev-client
&client_secret=dev-secret
&scope=openid dev-api
&username=admin@this.ws
&password=321ChangeMe!

###
POST {{url}}/workspace/059ce94f-63d3-47bc-bd4a-773ceb41fbfd/clone
{{auth}}
###
GET {{url}}/workspace/059ce94f-63d3-47bc-bd4a-773ceb41fbfd
{{auth}}
###
GET {{url}}/workspaces?term=
{{auth}}
###
DELETE {{url}}/workspace/cf4d217717b5454ca893b3ee8469c796
{{auth}}
###

POST {{url}}/template
{{json}}

{
    "name": "new template"
}

###

PUT {{url}}/template
{{json}}

{
    "id": 1,
    "name": "template"
}

###

DELETE {{url}}/template/1
